# Generated by Django 4.0.5 on 2022-06-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipmentList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JOBID', models.CharField(max_length=20, unique=True)),
                ('client', models.CharField(max_length=255)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('well', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(default='Iraq', max_length=255)),
                ('BU', models.CharField(blank=True, default='KIU', max_length=3, null=True)),
                ('BL', models.CharField(blank=True, default='SWT', max_length=3, null=True)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('isContract', models.BooleanField(blank=True, default=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('h2s', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('co2', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('oilRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('gasRate', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['client'],
            },
        ),
        migrations.CreateModel(
            name='JobMasterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.ManyToManyField(null=True, to='equipmentList.equipment_db')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobsdb')),
            ],
            options={
                'ordering': ['job'],
            },
        ),
    ]
