# Generated by Django 4.0.5 on 2022-06-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobsdb_co2_alter_jobsdb_h2s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdb',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdb',
            name='gasRate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdb',
            name='oilRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdb',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
