# Generated by Django 4.0.5 on 2022-06-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentList', '0001_initial'),
        ('jobs', '0003_alter_jobsdb_created_alter_jobsdb_gasrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmasterinfo',
            name='assets',
        ),
        migrations.AddField(
            model_name='jobmasterinfo',
            name='asset',
            field=models.ManyToManyField(to='equipmentList.equipment_db'),
        ),
    ]
