# Generated by Django 4.0.5 on 2022-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobmasterinfo_assets_jobmasterinfo_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdb',
            name='gen_JOBID',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobsdb',
            name='tag_client',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
