# Generated by Django 4.0.5 on 2022-07-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobsdb_gen_jobid_jobsdb_tag_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdb',
            name='get_id',
            field=models.TextField(default='', max_length=10),
        ),
    ]
