# Generated by Django 4.0.5 on 2022-07-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobsdb_get_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdb',
            name='get_id',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
