# Generated by Django 4.0.5 on 2022-06-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EQUIPMENT_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_num', models.CharField(max_length=200, unique=True)),
                ('serial_num', models.CharField(blank=True, max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('BU', models.CharField(blank=True, max_length=4, null=True)),
                ('BL', models.CharField(blank=True, max_length=4, null=True)),
                ('asset_life', models.IntegerField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tot_dep_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nbv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('temp_location', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['serial_num'],
            },
        ),
    ]
