# Generated by Django 4.0.5 on 2022-07-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentList', '0002_alter_equipment_db_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_db',
            name='file_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
