# Generated by Django 4.0.5 on 2022-07-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentMaintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedb',
            name='file_link',
            field=models.URLField(null=True),
        ),
    ]
