# Generated by Django 4.0.5 on 2022-07-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentMaintenance', '0002_maintenancedb_file_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedb',
            name='file_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
